settings:
  sampling: "uniform_proportional"
    total_points: 500000
  num_boxes: 10
  xmax: 256
  ymax: 256
  zmax: 0
  xmin: 0
  ymin: 0
  zmin: 0
  
  wmax: 10
  hmax: 10
  lmax: 10
  wmin: 10
  hmin: 10
  lmin: 10
  save_folder: '~/datasets/epd/10boxSq/processed'
  visu: true
