settings:
  sampling: "velodyne"
  num_boxes: 50
  xmax: 128
  ymax: 128
  zmax: 0
  xmin: 0
  ymin: 0
  zmin: 0
  
  wmax: 5
  hmax: 5
  lmax: 5
  wmin: 5
  hmin: 5
  lmin: 5
  save: false
  save_folder: '~/datasets/epd/50boxSq_light_velodyne_bulk/processed'
  visu: false
  # Gen in bulk is used to generate several scenes per mode
  gen_in_bulk: True
  # specify the number of scenes to generate for each mode
  # The modes can be 'train', 'val' and 'test'
  train: 80
  val: 10
  test: 10
  min_dist: 0.5
